controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
category_create:
    path: /categories/create
    controller: App\Controller\CategoryController::createCategory
admin_app_login:
    path: /admin/login
    controller: App\Controller\AdminLoginController::login
#/movies/{id}', name: 'app_movie_view'
app_movie_view:
    path: /movies/{id}
    controller: App\Controller\MovieController::view
